### ISSUE TITLE
Unlink role id from User before attempting to delete a Role resource

### ISSUE THREAD

**Issue by IyadAssaf** [form3tech-oss/terraform-provider-form3#93]
User contains an array of "role_ids" containing associated roles. Before deleting a role the provider should remove the role id from the user.

PR in progress - https://github.com/form3tech-oss/terraform-provider-form3/pull/96

**Comment by andykuszyk** [comment]
- [ ] Get tests to pass and merge.
 - [ ] Deploy changes to the provider via the bundler
 - [ ] Check that this works on a development environment

**Comment by andykuszyk** [comment]
Triggered by https://github.com/form3tech/infrastructure-api-customer-configuration/pull/664/files#diff-a2b113fd73a3b2e80e97bba87a08aa06L147

Current failure can be replicated with `TF_ACC=1 go test -v -run TestAccRole_destroyWithoutUser ./...`

**Comment by andykuszyk** [comment]
Current issue is:

* When a role is removed that is associated with a user...
* A 400 is returned from `securityapi`: `Cannot delete a role which is associated to a user.`
* This is expected behaviour.

We need to upgrade provider to remove the association from the user first.

**Comment by andykuszyk** [comment]
Potential fix pushed to https://github.com/form3tech-oss/terraform-provider-form3/pull/96/files, albeit with one remaining `TODO`.

Need to discuss approach before continuing - do we really want to be fetching all users on every deleted role?

**Comment by andykuszyk** [comment]
This issue is actually expected behaviour and therefore does not need a fix.
